-- Marken OS · 0003 · Purge demo data  [OPTIONAL — DESTRUCTIVE]
--
-- Run this ONLY if you accept losing the current demo content:
--   3 users · 1 project · 1 member · 1 submission · 4 comments · 2 notifications · 34 attendance rows
--
-- Why this is the recommended path: moving to Supabase Auth means passwords
-- cannot carry across regardless — bcrypt hashes are generated by Supabase, and
-- the three plaintext passwords in public.users have no migration path. Those
-- accounts must be re-created through an invite either way. Purging removes the
-- need for a username-to-UUID transition period across seven tables, for the
-- sake of one demo project.
--
-- Skip this file if the attendance history matters. If you skip it, 0004 still
-- runs, but the legacy text columns stay populated and need backfilling by hand
-- once real accounts exist.

begin;

delete from public.notifications;
delete from public.comments;
delete from public.submissions;
delete from public.project_members;
delete from public.projects;
delete from public.attendance;
delete from public.clients;
delete from public.users;

commit;
